/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package contract.client.gradle.sample;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
